FROM python:3.10-slim as base

RUN mkdir -p /app
RUN mkdir -p /dagster/dagster_home
RUN touch /dagster/dagster_home/dagster.yaml

COPY . /app

WORKDIR /app
RUN pip install -e ".[dev]"

EXPOSE 3000

CMD ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000"]
